### ISSUE TITLE
Running the game tries to launch another instance of mod organizer

### ISSUE THREAD

**Issue by TheRedBaron56** [rockerbacon/modorganizer2-linux-installer#454] opened 2023-02-17 16:11 UTC
mo2 starts without issue. try to run the nvse, cmd runs FalloutNVLauncher.exe. 

![Screenshot from 2023-02-17 11-07-20](https://user-images.githubusercontent.com/72238503/219705221-adf980b8-7eaf-4eaf-8338-56cfc021169d.png)
(couldn't copy the code for some reason)
Then I get the window popup _An instance of Mod Organizer is already running._

Tried to run New Vegas; same result. Tried Fallout Launcher; same result.
Tried reinstalling mo2. Still didn't work. Tried downloading a new copy of the mo2 installer; installed using that. Still didn't work.
Don't know why this is happening; ran the game fine yesterday and I haven't installed any new mods.

**Comment by poxy100** [comment] 2023-03-01 04:23
I appear to be getting the same issue, were you able to find a solution?

**Comment by ParzivalWolfram** [comment] 2023-03-14 09:42
I've had the same issue for about a month now, as well. NVSE does load correctly, but then relaunches the fake launcher. If you have the 4GB patch, that also loads NVSE, which seems to do the same thing in that situation as well.

**Comment by ConvexTlc97** [comment] 2023-03-15 23:28
> I've had the same issue for about a month now, as well. NVSE does load correctly, but then relaunches the fake launcher. If you have the 4GB patch, that also loads NVSE, which seems to do the same thing in that situation as well. If you open MO2, then rename the fake launcher to something else, and rename the actual launcher properly, everything works again for that launch.

Not sure what you mean. What files are you renaming? I am having the same issue.

**Comment by ParzivalWolfram** [comment] 2023-03-16 05:46
The MO2 install script renames the original launcher to
`_FalloutNVLauncher.exe`. You have to swap this file back in as the actual
launcher (remove the underscore) after launching MO2. Leaving the normal
launcher as the current launcher place seems to work if you launch the NVSE
EXE directly, but I haven't tested that super well.

**Comment by poxy100** [comment] 2023-03-20 03:33
okay so were somewhere forward. if its just a matter of adding a "_" to the exe file, would it be difficult to tweek MO or NVSE to just launch that _version instead of doing it manually every time? im kinda looking for a way I can use it in the decks default mode.

**Comment by poxy100** [comment] 2023-03-20 05:22
I've been messing around with the exe files, if you rename the exe files back to original and add MO2's exe to steam, you can still run it in either mode, this gets rid of the loop, but then the game just won't run at all. the NVSE and fallout NV options wont do anything, the launcher however runs, but it thinks that the game isn't installed.

Im not an expert, but to me it just seems like there no simple fix here, either way it only goes half way, 

This is why I hate having to mod using a manager. why I hate secondary systems to begin with. why can I not just install them manually? I've been trying for months to carry over my TTW install to the deck but because of this I've even lost the install I had in the first place. its... it just so frustrating.

**Comment by MrRollton** [comment] 2023-07-29 22:07
Looks like the cause of the issue is the same as in #387 . Try repeating the steps I provided there.

**Comment by rockerbacon** [comment] 2024-01-09 18:45
Duplicate of #387

**Closed by rockerbacon** 2024-01-09 18:45 UTC
Labels: newvegas
