### ISSUE TITLE
MO2 Installation - Cannot Locate FalloutSteamLauncher.exe

### ISSUE THREAD

**Issue by vlexpee** [rockerbacon/modorganizer2-linux-installer#677] opened 2024-06-07 15:13 UTC
Good Morning,

For FO3 GOTY I had already successfully installed MO2, but was unable to get FOSE to install correctly. Mods that required FOSE were not working for me and I was okay, but now it all stopped working after 2 months.

It started launching to the game launcher, and not MO2. I ended up uninstalling the game along with deleting the contents that the MO2 installation created.

Now i am trying to reinstall MO2, but the first error that I ran into, is when I run the ,/install.sh command, I get a pop up that FO3 cannot be located in my game directory even though it's installed. 

I found a workaround browsing here that I needed to enter;

STEAM_LIBRARY='location of where FO3 is installed' ./install.sh

I got the game install location from steam, by going to the game and browsing local files.

Now the command runs the installation up to a certain point.

I do not have the log at the moment, but the error notification reads that it cannot locate FalloutSteamLauncher.exe in the directory

I browsed the game folder and I do not see that exe located in there.

I cannot find any other fixes for this.

Any help is appreciated.

Thank you,

**Comment by rockerbacon** [comment] 2024-06-07 18:05
Duplicate of #676

**Closed by rockerbacon** 2024-06-07 18:05 UTC
