### ISSUE TITLE
Nothing Starting from Steam after installing.

### ISSUE THREAD

**Issue by Eisdaemon** [rockerbacon/modorganizer2-linux-installer#671] opened 2024-05-27 21:07 UTC
I have Fallout 4 installed and wanted to install MO2. 
After using it, Nothing starts through steam anymore. If I verify the integrity of the files, Fallout starts again as normally. 

I have steam installed through flatpak as well as protontricks. I had no error during installation. I use KDE Neon 6.0, so Ubuntu based.

**Comment by rockerbacon** [comment] 2024-05-29 01:05
Duplicate of #656

**Closed by rockerbacon** 2024-05-29 01:05 UTC
