### ISSUE TITLE
Mod Organizer automatically closes after running game in Steam using Flatpak

### ISSUE THREAD

**Issue by sergiofenoll** [rockerbacon/modorganizer2-linux-installer#296] opened 2022-01-21 19:00 UTC
After clicking on Run inside the Steam library, a terminal launches and immediately closes.

After hitting my head against many proverbial walls, I found a solution for this: set the install folder of the Mod Organizer instance inside the install folder of the game I'm trying to mod (Oblivion for me).

By default Mod Organizer gets installed to `$HOME/Games/mod-organizer2-$NAME_OF_GAME`, and that would break, but if I install it in `$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Oblivion/modorganizer2-install-path`, it works!

I assume it's due to the access rights of the game itself (iirc Steam now containerizes games? so presumably an executable ran by Steam won't be able to read files in `~/Games`, but is fine with reading them inside it's container).

Wanted to share it in case others encounter this same issue.

**Comment by rockerbacon** [comment] 2022-01-24 18:16
Duplicate of #285

**Closed by rockerbacon** 2022-01-24 18:16 UTC
Labels: duplicate
