### ISSUE TITLE
NXM links don't download properly

### ISSUE THREAD

**Issue by TheRedBaron56** [rockerbacon/modorganizer2-linux-installer#475] opened 2023-05-23 18:17 UTC
When downloading a mod from nexus with 'mod manager download' option, the download fails immediately. It does not do this while mo2 is closed; it opens the manager and the download goes through. But if the manager is open when I start the download, it fails. 

I have already looked around and found this thread:[https://github.com/rockerbacon/modorganizer2-linux-installer/issues/355](url) and others like it. I am confident my issue stems from a different error: I'm using the latest version of protontricks (1.10.3) installed through pipx, on Mint Cinnnamon 21.1

**Comment by Cubeson** [comment] 2023-07-15 09:23
I have the same issue, also Mint Cinnnamon 21.1

**Comment by rockerbacon** [comment] 2023-07-17 18:32
Duplicate of #317

**Closed by rockerbacon** 2023-07-17 18:32 UTC
