### ISSUE TITLE
Cannot Start Deck - file does not exist. [Steam Deck]

### ISSUE THREAD

**Issue by aFriendlyHobo** [rockerbacon/modorganizer2-linux-installer#607] opened 2024-04-21 15:23 UTC
Hello,

I've been searching through the issues tab for a few hours today, and I've discovered a few issues. One of them was the fairly regular No Prefix error, which I circumvented by saying no when the text box pops up during installation, which allows MO2 to finish it's install. 

When I try to run New Vegas on my Steam Deck however, I get the following error notice, and I've not seen it come up in the issues section yet, so I thought I'd post it. I'm unsure on how to proceed, or even what it means. 

NV is installed on my Deck's SSD, while MO2 is installed on my portable SD card (so I can move mods between PC and Steam Deck). 

![steamuserimages-a akamaihd](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/65201137/cdbea2cb-7c1e-49a0-ba9f-d15350d489f6)

**Comment by rockerbacon** [comment] 2024-04-21 16:23
Duplicate of #387

Additionaly:

> NV is installed on my Deck's SSD, while MO2 is installed on my portable SD card (so I can move mods between PC and Steam Deck).

That won’t work because USVFS does not cross filesystem boundaries. You need to have the game and MO2 in the same filesystem.

**Closed by rockerbacon** 2024-04-21 16:23 UTC
