### ISSUE TITLE
ERROR: cannot execute 'Z' - No such file or directory

### ISSUE THREAD

**Issue by salihmarangoz** [rockerbacon/modorganizer2-linux-installer#638] opened 2024-05-07 23:07 UTC
Installed Skyrim SE with Proton 8 and it isn't working. I can run MO2 by starting explorer using protontricks, however, it doesn't run with your steam redirector.

instance_path.txt:
```
Z:\otherssd\Skyrim\mo2\modorganizer2\ModOrganizer.exe
```

Proton Log:
```
INFO: read executable location 'Z'
ERROR: cannot execute 'Z' - No such file or directory
```

**Comment by salihmarangoz** [comment] 2024-05-07 23:41
Adding this solved the problem:
```
STEAM_COMPAT_MOUNTS=/otherssd/Skyrim/mo2 %command%
```
However, I still don't know why because SkyrimSE is located in "/otherssd/SteamLibrary/steamapps/common/Skyrim Special Edition" which is the same SSD device.

**Comment by rockerbacon** [comment] 2024-05-08 08:55
The location ‘Z’ thing is just a log issue. The windows C libs are a mess, sometimes you use wide chars, sometimes standard chars with utf-8 encoding and I just didn’t bother dealing with it for the logs.

This is a duplicate of #285.

**Closed by rockerbacon** 2024-05-08 08:55 UTC
