### ISSUE TITLE
Performance issues when running FO4 via MO2

### ISSUE THREAD

**Issue by Rabcor** [rockerbacon/modorganizer2-linux-installer#332] opened 2022-04-25 23:13 UTC
I'm trying to play Fallout 4 with the mod organizer.

If I try to launch the game with the alternate launcher created by the installer, the game will not run.

If I open the mod organizer: `prime-run protontricks-launch --appid 377160 /run/media/rabcor/KingSpec/Games/Mod-Organizer2/modorganizer2/ModOrganizer.exe ` and launch the game from there.

It actually does launch the game, but performance is borked (this happens even on a blank profile with no mods and without using f4se; if I launch the game normally through the original launcher performance is about as good as it gets for this game, most of the time I'm at 144hz (refresh rate), rarely dip below 100, but when I launch with MO2 i'll find myself at 10-30fps a lot of the time).

I tried creating a shortcut from MO2 to launch the game as well, it just gave the same result.

Note: I couldn't figure out a solution for this, but I ended up just manually installing all my mods and then running it from steam. If I'm the only one having the issue, only thing I can think of is that it might have something to do with my filesystem which for the drive mod organizer and fo4 are installed on is XFS.

**Comment by MySTerY1747** [comment] 2022-05-12 13:28
Any progress with this? I have the exact same problem with SkyrimSE. On Windows I get a steady 60 fps, but on Linux it's completely unplayable, mostly below 20fps.

**Comment by Nyonyix** [comment] 2022-06-03 00:10
Adding my own to make this issue more visible. Launching without MO2 I get a solid 144 and 40-50% gpu, Even f4se seems fine redirecting the launcher.

Launch f4se with MO2 and I'm at 70-80 fps dropping to 40 in downtown with 90% gpu at all times.

**Comment by mlgomez** [comment] 2022-07-20 12:46
There appears to be some overhead caused by how MO2 runs under Proton. I have a pretty heavily-modded version of SkyrimSE, but when running with the old Lutris installer I had a solid 60 FPS on my 1070 Ti. Launching with the same mods with the Steam Proton version with the new install script, FPS drops sometimes to the 40s.

The activation and installation of mods also appears to slow down as the program remains open. Restarting it removes the lag until about 15-20 minutes pass and it reappears. During my process of re-adding mods while experimenting with the newer MO2 running under Proton, I had to restart every 4-5 mods while testing. It's not unbearable, but something in this new method is definitely causing problems and turning the GPU into a bitcoin miner.

**Comment by EarlOfMagadan** [comment] 2023-04-09 21:12
@mlgomez I'm experiencing this too, this needs to be looked into.

**Comment by rockerbacon** [comment] 2024-01-25 10:45
I'm closing this because such issue would lie somewhere in Proton, Wine, DXVK or MO2 and there's nothing that can be done by the installer. Original issue creator is also running the game with protontricks-launch, which the [post-install instructions explicitly advise against](https://github.com/rockerbacon/modorganizer2-linux-installer/blob/master/post-install.md#launching-mod-organizer-2-outside-of-steam).

If anyone has something actionable to report, please do so at the issue tracker of the relevant project.

**Closed by rockerbacon** 2024-01-25 10:45 UTC
