### ISSUE TITLE
Please Help! 

### ISSUE THREAD

**Issue by Mattster28** [rockerbacon/modorganizer2-linux-installer#602] opened 2024-04-20 06:09 UTC
I’m trying to play Fallout New Vegas on Steam Deck with Mods but when I try to install the MO2installer in the Konsole it says “Operation canceled. Check the terminal for details” right before it’s done. Does anyone know how I can fix this? Thank you!

**Comment by cprin21** [comment] 2024-04-20 07:44
Hi, please paste the terminal's output, specifically the line where it fails. Other issues have been made about wget being a problem so if it's an issue with the JDK not being found in /tmp, check out issue #596

**Comment by cprin21** [comment] 2024-04-20 07:58
I have posted a quick fix to force the use of curl instead of wget. see https://github.com/rockerbacon/modorganizer2-linux-installer/issues/601#issuecomment-2067595587

**Comment by rockerbacon** [comment] 2024-04-20 10:16
Report doesn’t include sufficient information. Likely a duplicate of recent wget issues

**Comment by Mattster28** [comment] 2024-04-20 12:28
I tried the quick fix for #601 but I’m still getting this error pop up. 
![IMG_8456](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/167602349/7a64eca9-0ade-4fcb-8601-59977235a6cf)

**Comment by Mattster28** [comment] 2024-04-20 12:37
INFO: all dependencies met
INFO: selected game 'newvegas'
INFO: found Steam in '/home/deck/.local/share/Steam'
INFO: steam not found in '/home/deck/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/deck/.local/share/Steam'
INFO: selected install directory '/home/deck/Games/mod-organizer-2-newvegas'
INFO: using curl backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: using curl backend
INFO: fetching remote resource at 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z'
INFO: downloading 'https://github.com/ModOrganizer2/modorganizer/releases/download/v2.4.4/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z' to '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: using curl backend
INFO: fetching remote resource at 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks'
INFO: downloading 'https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks' to '/tmp/mo2-linux-installer-downloads-cache/winetricks'
INFO: using curl backend
INFO: fetching remote resource at 'https://github.com/xNVSE/NVSE/releases/download/6.2.4/nvse_6_2_4.7z'
INFO: downloading 'https://github.com/xNVSE/NVSE/releases/download/6.2.4/nvse_6_2_4.7z' to '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z'
INFO: extracting '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z' to '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4'
INFO: removing existing JDK installation in '/home/deck/.local/share/Steam/steamapps/compatdata/22380/pfx/drive_c/java'
INFO: installing JDK in '/home/deck/.local/share/Steam/steamapps/compatdata/22380/pfx/drive_c/java'
INFO: installing Mod Organizer 2 in '/home/deck/Games/mod-organizer-2-newvegas/modorganizer2'
INFO: installing script extender in '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas'
INFO: copying all files from '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4' into '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas'
cp: not replacing '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas/Data/NVSE/nvse_config.ini'
cp: not replacing '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas/nvse_1_4.dll'
cp: not replacing '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas/nvse_editor_1_4.dll'
cp: not replacing '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas/nvse_loader.exe'
cp: not replacing '/home/deck/.local/share/Steam/steamapps/common/Fallout New Vegas/nvse_steam_loader.dll'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/newvegas_nvse_6_2_4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4.7z'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/Mod.Organizer-2.4.4'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07'
INFO: removing '/tmp/mo2-linux-installer-downloads-cache/winetricks'

**Comment by rockerbacon** [comment] 2024-04-21 15:57
Reopening since the logs show it’s not related to #596. 

Where did you get the installer? Your print suggests usage of an outdated version

**Comment by dottools** [comment] 2024-04-21 17:12
I am running into the exact same issue and I used the latest release from this git repository: https://github.com/rockerbacon/modorganizer2-linux-installer/releases/download/4.6.1/mo2installer-4.6.1.tar.gz

**Comment by dottools** [comment] 2024-04-21 17:41
**Platform info**:
Operating System: SteamOS 3.5.17
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.107.0
Qt Version: 5.15.9
Kernel Version: 6.1.52-valve16-1-neptune-61 (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Custom APU 0932
Memory: 14.5 GiB of RAM
Graphics Processor: AMD Radeon Graphics
Manufacturer: Valve
Product Name: Galileo
System Version: 1

Terminal log dump:
[modorganizer install log.txt](https://github.com/rockerbacon/modorganizer2-linux-installer/files/15052886/modorganizer.install.log.txt)

**Comment by rockerbacon** [comment] 2024-04-21 18:08
@dottools your issue is completely different. You can open a separate issue if you wish, but it looks like an issue with Winetricks being unable to download some files.

**Comment by dottools** [comment] 2024-04-21 18:19
@rockerbacon Oh interesting it is a bit different. I resolved it just by re-running the install process and not recreating the game prefix, and select Update then it completed successfully.

Thanks.

**Comment by rockerbacon** [comment] 2024-06-10 23:48
Closing as stale

**Closed by rockerbacon** 2024-06-10 23:48 UTC
Labels: question
