### ISSUE TITLE
MO2 isn't opening up after running ./install.sh

### ISSUE THREAD

**Issue by WTFFranceRM** [rockerbacon/modorganizer2-linux-installer#547] opened 2023-12-05 20:02 UTC
Bronoc-IdeaPad:~/Downloads/Untitled Folder$ ./install.sh
INFO: all dependencies met
INFO: selected game 'skyrim'
INFO: found Steam in '/home/ryan/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/ryan/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: found Steam in '/home/ryan/.var/app/com.valvesoftware.Steam/.local/share/Steam'

I am using the flatpak version of Steam.

**Comment by WTFFranceRM** [comment] 2023-12-05 20:06
I've been using SteamTinker. I decided to use this installer in hope that my Skyrim: LE game doesn't encounter an audio bug (Voiceless NPCs and no music).

**Comment by MrShelbySann** [comment] 2023-12-13 01:49
Same issue here 
```
mo2installer-4.4.0 ./install.sh
INFO: all dependencies met
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/mathieu/.local/share/Steam'
INFO: game not found in '/home/mathieu/.local/share/Steam'
INFO: game found in '/media/Jeux/SteamLibrary'
INFO: steam not found in '/home/mathieu/.var/app/com.valvesoftware.Steam/.local/share/Steam'
```

**Comment by rockerbacon** [comment] 2023-12-15 10:13
Duplicate of #530

**Closed by rockerbacon** 2023-12-15 10:13 UTC
