### ISSUE TITLE
MO2 Not Found

### ISSUE THREAD

**Issue by GodPhase777** [rockerbacon/modorganizer2-linux-installer#672] opened 2024-05-29 05:08 UTC
Any time I install and attempt to launch New Vegas it says MO2 isn't in the directory. I attempted to copy the install of MO2 to the specified directory, but it won't open MO2 successfully then, and seems to get confused thinking its already open and trying to open it more.

`Error 2 ERROR_FILE_NOT_FOUND: Filenotfound. (0x2)
 . binary: 'Z:\home\deck\.local\share\Steam\steamapps\common\Fallout New Vegas\Vegas\modorganizer2\ModOrganizer.exe'`

Any help would be great. I'm using the latest SteamOS, and am using a steam deck.

**Comment by rockerbacon** [comment] 2024-05-29 08:37
Duplicate of #656

**Closed by rockerbacon** 2024-05-29 08:37 UTC
