### ISSUE TITLE
Oblivion no longer launching

### ISSUE THREAD

**Issue by AnotherTieflingBard** [rockerbacon/modorganizer2-linux-installer#406] opened 2022-10-13 22:23 UTC
It creates a popup that says "an error occurred: Failed to save '{}', could not create a temporary file: {} (error {})" 

This happens no matter how many times you freshly install both the game and the mod organizer

**Comment by Razatop** [comment] 2022-10-14 23:46
Getting this to after installing (Or rather trying to install [Compat patches for Unique Landscapes](https://www.nexusmods.com/oblivion/mods/13834/)) Anything like this for you? Also uploading your dump log would probably help  :D

**Comment by rockerbacon** [comment] 2023-07-17 20:37
Duplicate of #407

**Closed by rockerbacon** 2023-07-17 20:37 UTC
Labels: duplicate
