### ISSUE TITLE
Looking for File in wrong place?

### ISSUE THREAD

**Issue by CreativeGrey** [rockerbacon/modorganizer2-linux-installer#489] opened 2023-07-09 05:03 UTC
After installing 4.3.0 for New Vegas, I try to start it and get the error message

![image](https://github.com/rockerbacon/modorganizer2-linux-installer/assets/16735997/1172c8f1-1cbd-456a-8606-94ea203eb32c)

As far as I can tell, unless New Vegas does it wildly differently for some reason, it shouldn't even be looking here for this exe to begin with.

Making a link from where its looking to where it is seems to fix it, but its weird it was trying this in the first place.

Running linux mint.

Edit: I think this fix caused some permissions issues? When I try to launch through MO2 it gives an access denied error, and trying to launch nvse directly says it can't find the games exe. Giving up for tonight, maybe it will have magically fixed itself when I load up my computer tomorrow.

**Comment by P14y3r1** [comment] 2023-11-26 03:57
Hey sorry to ask a question this long after you posted this, but have you any idea how I can work around this, im on my steam deck and im running into the same issue and I have literally zero idea on how I could fix/workaround it, if you know that would be a huge help.

**Comment by CreativeGrey** [comment] 2023-11-27 02:05
It has been a while, I decided to try it again to see if I could replicate the issue. I did, and my workaround above worked, but now I have something else.

If you want to try this workaround. Try right clicking and adding a new link to file or directory at the location its looking for the exe. You might have to make a new folder or two as well to get it to work.

I also did some testing just with regular mod organizer and running it with proton ge 8 or above, that was able to work once I'd reinstalled FNV to get rid of this version. So if the above method gives you trouble you can try that one.

**Comment by rockerbacon** [comment] 2024-01-09 18:43
Duplicate of #454

**Closed by rockerbacon** 2024-01-09 18:43 UTC
