### ISSUE TITLE
Cannot create tmp dir

### ISSUE THREAD

**Issue by G4CHIM4STER** [rockerbacon/modorganizer2-linux-installer#578] opened 2024-02-20 20:53 UTC
Hello there. I'm trying to install MO2 for my Fallout 4 and whie i'm running an install script there appears an error.

Here is error logs:

```sh
INFO: all dependencies met
INFO: selected game 'fallout4'
INFO: found Steam in '/home/g4chi/.local/share/Steam'
INFO: steam not found in '/home/g4chi/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/g4chi/.local/share/Steam'

(zenity:58120): Gtk-CRITICAL **: 23:44:48.035: GtkBox 0x588fe4adcfd0 reports a minimum height of 216, but minimum height for width of 1048576 is 226. Expect overlapping widgets.

(zenity:58120): Gtk-CRITICAL **: 23:44:48.035: GtkBox 0x588fe4b62700 reports a minimum height of 119, but minimum height for width of 1048576 is 129. Expect overlapping widgets.
INFO: proceeding with existing prefix
INFO: user confirmed prefix setup
INFO: selected install directory '/home/g4chi/Games/mod-organizer-2-fallout4'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
mkdir: cannot create directoy «/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07»: Access denied
```
Can anyone help me with it ?

**Comment by rockerbacon** [comment] 2024-02-21 16:14
Duplicate of #335

**Closed by rockerbacon** 2024-02-21 16:14 UTC
