### ISSUE TITLE
Issue when installing on steam deck. 

### ISSUE THREAD

**Issue by FoxinTale** [rockerbacon/modorganizer2-linux-installer#562] opened 2024-01-21 22:55 UTC
It is finding the game location and steam, but also not finding steam.
Opening terminal in the folder of mo3installer, and executing just "./install.sh" alone works, brings up the GUI to select the game and all.
I can select the game (tested on both Fallout 4 and Skyrim Special Edition) but that's as far as I get.
 
In the console I see:
```
(deck@steamdeck mo2installer-4.4.0)$ ./install.sh
INFO: All dependencies met
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/deck/.local/share/Steam'
INFO: game found in '/home/deck/.local/share/Steam'
INFO: : steam not found in 'home/deck/.var/app/com.valvesoftware.Steam/.local/share/Steam'
(1)(deck@steamdeck mo2installer-4.4.0)$
```
And that's it. 

Other things and notes: 
- While I do have a micro SD in, both SSE and Fallout 4 are installed on the internal SSD.
- Steam is installed as the version that came with SteamOS, not flatpack.
- Protontricks is from the discover store. 
- Tried on both master and latest (4.4.0) release. Same results. 
-  Fallout 4 and SSE have the same results.
- I did copy over a downgraded SSE from my Windows PC, but given that this is also happening with FO4, I don't think this could be causing the problem.

Not sure what else I can provide to help figure this out, as I've been at this for the last day or so, tracing through each script to see if I could manually do it before giving up.  Could be a script issue, or user error. With my luck it's probably user error.

**Comment by rockerbacon** [comment] 2024-01-22 14:01
Duplicate of #530

**Closed by rockerbacon** 2024-01-22 14:01 UTC
Labels: duplicate

**Comment by FoxinTale** [comment] 2024-01-23 02:57
> Duplicate of #530

Here's the thing, the fixes suggested in that issue don't work.
I can't (or,. rather don't think I should) install protontricks through the flatpak option when it explicitly states "If using a steam deck it must be installed through discover" 

Trying it in a new shell session, didn't work. 

I'm not sure what else I can do other than just trace through each step of the script and do it manually. Step by step, this time on a mind that isn't fried by lack of sleep.

**Comment by rockerbacon** [comment] 2024-01-23 15:27
@FoxinTale we remove duplicate issues because the goal of the issue tracker is to identify and permanently fix problems and spreading information about the same behaviour across multiple threads makes this significantly more difficult.

The aforementioned issue is still open, meaning the problem does not currently have a fix, even if other users may have found workarounds for their specific systems.

**Comment by FoxinTale** [comment] 2024-01-24 03:13
> @FoxinTale we remove duplicate issues because the goal of the issue tracker is to identify and permanently fix problems and spreading information about the same behaviour across multiple threads makes this significantly more difficult.
> 
> The aforementioned issue is still open, meaning the problem does not currently have a fix, even if other users may have found workarounds for their specific systems.

Aye, fair enough mate. I'll do what I can to help get to the bottom over on that issue.
