### ISSUE TITLE
Launching Game does not Seem to do anything

### ISSUE THREAD

**Issue by TheFibonacciEffect** [rockerbacon/modorganizer2-linux-installer#725] opened 2024-08-18 20:55 UTC
I am using Arch, I followed the instructions, creating a new prefix when it was recommended to me and launching the game (Skyrim Special Edition) once using proton 9.0-2. Then I proceded the setup, however when clicking launch game in the skyrim UI, nothing seems to happen. Nothing is launched. 
I am using the flatpak version of steam and the protontricks version from my package manager. The directory `/run/user/1000/doc/190ead89/Steam` does indeed not seem to exist.

What can I do to debug this?

Here are some logs:
```
INFO: selected game 'skyrimspecialedition'
INFO: found Steam in '/home/caspar/.steam'
grep: /home/caspar/.steam/steam/steamapps/libraryfolders.vdf: No such file or directory
INFO: found Steam in '/home/caspar/.var/app/com.valvesoftware.Steam/.local/share/Steam'
INFO: game found in '/home/caspar/.var/app/com.valvesoftware.Steam/.local/share/Steam'
protontricks (WARNING): Steam library folder /run/user/1000/doc/190ead89/Steam not found. Protontricks might not have access to the directory.
protontricks (WARNING): Steam library folder /run/user/1000/doc/190ead89/Steam not found. Protontricks might not have access to the directory.
pressure-vessel-wrap[11816]: W: Not sharing path --filesystem="/etc" with container because "/etc" is reserved by the container framework
pressure-vessel-wrap[11816]: W: Not sharing path --filesystem="/sbin" with container because "/sbin" is reserved by the container framework


INFO: moving '/home/caspar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/489830' to '/home/caspar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/489830.20240818224123'

INFO: user confirmed prefix setup
protontricks (WARNING): Steam library folder /run/user/1000/doc/190ead89/Steam not found. Protontricks might not have access to the directory.
protontricks (WARNING): Steam library folder /run/user/1000/doc/190ead89/Steam not found. Protontricks might not have access to the directory.
pressure-vessel-wrap[13702]: W: Not sharing path --filesystem="/etc" with container because "/etc" is reserved by the container framework
pressure-vessel-wrap[13702]: W: Not sharing path --filesystem="/sbin" with container because "/sbin" is reserved by the container framework
INFO: achiving '/home/caspar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/489830/pfx/drive_c/users' to '/home/caspar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/489830/pfx/drive_c/users.bak'
INFO: moving '/home/caspar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/489830.20240818224123/pfx/drive_c/users' to '/home/caspar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/489830/pfx/drive_c/users'

INFO: selected install directory '/home/caspar/Games/mod-organizer-2-skyrimspecialedition'
INFO: using wget backend
INFO: fetching remote resource at 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'
INFO: downloading 'https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u312-b07/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip' to '/tmp/mo2-linux-installer-downloads-cache/OpenJDK8U-jre_x64_windows_hotspot_8u312b07.zip'



protontricks (WARNING): Steam library folder /run/user/1000/doc/190ead89/Steam not found. Protontricks might not have access to the directory.
pressure-vessel-wrap[15150]: W: Not sharing path --filesystem="/etc" with container because "/etc" is reserved by the container framework
pressure-vessel-wrap[15150]: W: Not sharing path --filesystem="/sbin" with container because "/sbin" is reserved by the container framework
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
warning: You apppear to be using Wine's new wow64 mode. Note that this is EXPERIMENTAL and not yet fully supported. If reporting an issue, be sure to mention this.
------------------------------------------------------
Using winetricks 20240105 - sha256sum: 8f28985b06e9e04b5268e2aef3429b2a0f6abd4fd12c4a30472dfe66355128fa with wine-9.0 and WINEARCH=win64
Using native override for following DLLs: xaudio2_7
Executing /home/caspar/.cache/protontricks/proton/Proton 9.0/bin/wine C:\windows\syswow64\regedit.exe /S C:\windows\Temp\_native\override-dll.reg
wine: using kernel write watches, use_kernel_writewatch 1.
fsync: up and running.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0070:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
Executing /home/caspar/.cache/protontricks/proton/Proton 9.0/bin/wine C:\windows\regedit.exe /S C:\windows\Temp\_native\override-dll.reg
wine: using kernel write watches, use_kernel_writewatch 1.
wineserver: using server-side synchronization.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
006c:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
wine: using kernel write watches, use_kernel_writewatch 1.
Executing mkdir -p /home/caspar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/_native
INFO: configuring mo2 executable path 'Z:\home\caspar\Games\mod-organizer-2-skyrimspecialedition\modorganizer2\ModOrganizer.exe' in '/home/caspar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Skyrim Special Edition/modorganizer2/instance_path.txt'
INFO: setting up redirector in '/home/caspar/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Skyrim Special Edition/SkyrimSELauncher.exe'
INFO: installation completed successfully
```

**Comment by TheFibonacciEffect** [comment] 2024-08-18 21:13
Here are the journal logs from steam after cleaning them a bit, but doesnt seem very helpful unfortunately:
[start-skyrim.log](https://github.com/user-attachments/files/16652147/start-skyrim.log)

**Comment by TheFibonacciEffect** [comment] 2024-08-18 21:27
Using the command `WINEESYNC=1 WINEFSYNC=1 protontricks-launch --appid 489830 "$HOME/.config/modorganizer2/instances/skyrimspecialedition/modorganizer2/ModOrganizer.exe"` from https://github.com/rockerbacon/modorganizer2-linux-installer/blob/master/post-install.md
does launch mod organizer, but I can not launch skyrim from the mod organizer

**Comment by rockerbacon** [comment] 2024-08-19 10:09
Duplicate of #656. Can probably be fixed by setting Flatpak permissions as described in #312

**Closed by rockerbacon** 2024-08-19 10:09 UTC
Labels: duplicate
