### ISSUE TITLE
MO2 Virtual File System not used by some programs

### ISSUE THREAD

**Issue by MrPhantom** [rockerbacon/modorganizer2-linux-installer#104] opened 2020-07-05 04:09 UTC
Most tools I run via Mod Organizer 2's execute function seem to automatically pick up the VFS and work flawlessly with minor or no tweaking. However, at least two - MO2's built in VFS browser using explorer++ and PoserDataGen, an animation list creator that's part of Poser Hotkeys SE - fail to use the VFS and instead work as if they were launched in WINE outside of Mod Organizer. I've verified that PoserDataGen otherwise works without issue by manually moving any required files into the Skyrim data folder and running it through MO2. 

The tools that do work (I've used FNIS, Wrye Bash, SSEdit and Bodyslide all without issues) detect my Skyrim SE install automatically and without my input, while PoserDataGen requires me to manually select the data folder. The VFS browser opens my install path automatically, however it doesn't properly load the VFS and instead shows the actual file listing of the Skyrim data folder.

I'm using Lutris 0.5.7 on Void Linux with my Steam library in the standard location under ~/.local/share/Steam, with MO2 installed using the 2.8.2 Stable installer. Whenever I'm prompted for a data path, I use ~/.local/share/Steam/steamapps/common/Skyrim Special Edition - is there another path I should be using, under the WINE filesystem or Steam compatdata folder, maybe?

**Comment by rockerbacon** [comment] 2020-07-05 17:21
MO2 VFS doesn't work perfectly out of the box with all external tools, that's just how it is. After reading Poser Hotkeys description on Nexus, it seems a specific setup might be necessary but the video explaining how to do it was taken down. You might need to create extra directories, configure specific "Start in" paths or something else, it depends on the tool. I would start by setting it like a ProcPatcher: set "start in" to the same directory where the executable resides, creating the directories if they don't exist.

The Explorer++ bug could not be reproduced, it can see all installed mods and resources just fine on my machine. It was configured out of the box to start in an inexistent directory, I had to manually change it to the game's install foder.

**Comment by MisterFox** [comment] 2020-12-11 03:45
I'm also having the issue where Explore Virtual Folder doesn't seem to be showing the version with the installed mods. While my SKSE and SkyrimSE launchers both do launch properly with my mods, I can't see them if I use the Explore Virtual Folder option (it shows a 'vanilla' Skyrim data folder) and I'm not able to run the Reqtificator properly, as it's only detecting the default files (it's throwing an exception saying that it can't find Requiem.esp despite it being recognized by Skyrim itself when I launch it through MO2)

Is there any info I can give that will be important for this?

My Steam library is in a custom folder, and I did run into an issue where the Lutris script was trying to hit an old install -- I fixed that and it's no longer trying to work from that to my knowledge, since all MO2 shortcuts are pointing to the proper directories.

For completeness, my binary and Start in for Skyrim Special Edition:

Binary: Z:\home\ose\SteamLibrary\steamapps\common\Skyrim Special Edition\SkyrimSE.exe
Start in: Z:\home\ose\SteamLibrary\steamapps\common\Skyrim Special Edition

My Binary, Start in, and Arguments for Explore Virtual Folder:

Binary: Z:\home\ose\Games\mod-organizer-2\ModOrganizer2\explorer++\Explorer++.exe
Start in: Z:\home\ose\Games\mod-organizer-2\ModOrganizer2\explorer++
Arguments: "Z:\home\ose\SteamLibrary\steamapps\common\Skyrim Special Edition\data"

I am using the latest .yml file as downloaded from this repo.

Thanks if you have time to help

**Comment by monomachos** [comment] 2020-12-12 07:26
I can confirm this bug happens to me. The VFS works fine when playing the game, but it doesn't seem to work with Explorer++.

**Comment by monomachos** [comment] 2020-12-12 18:44
I have this issue as well. I can get the VFS working with Nemesis or Explorer++ whereas it works when playing Skyrim.

**Comment by rockerbacon** [comment] 2024-05-16 22:16
Closing this, as there hasn't been any activity in quite a while.

**Closed by rockerbacon** 2024-05-16 22:16 UTC
Labels: bug, question
