### ISSUE TITLE
Corrupt prefix on Fallout 3 GOTY installation

### ISSUE THREAD

**Issue by balajsra** [rockerbacon/modorganizer2-linux-installer#76] opened 2020-06-06 04:24 UTC
# System Information

Apologies if I have not included enough information, please let me know if anything else is necessary to debug.

## System
OS:              Arch Linux rolling n/a
Arch:            x86_64
Kernel:          5.6.15-arch1-1
Desktop:         KDE
Display Server:  x11

## CPU
Vendor:          GenuineIntel
Model:           Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
Physical cores:  4
Logical cores:   4

## Memory
RAM:             15.6 GB
Swap:            16.0 GB

## Graphics
Vendor:          NVIDIA Corporation
OpenGL Renderer: GeForce GTX 1070/PCIe/SSE2
OpenGL Version:  4.6.0 NVIDIA 440.82
OpenGL Core:     4.6.0 NVIDIA 440.82
OpenGL ES:       OpenGL ES 3.2 NVIDIA 440.82
Vulkan:          Supported

## Installer
Version: 2.7.0 Stable

## Lutris
Version: 0.5.6

# Log Output
[lutris-mod-organizer.log](https://github.com/rockerbacon/lutris-skyrimse-installers/files/4739330/lutris-mod-organizer.log)

# Issue Description

I have the **Fallout 3 GOTY** and **Proton 5.0** directory in `$HOME/.local/share/Steam/steamapps/common` and (symlink) `$HOME/.steam/steam/steamapps/common`.

It appears that the installer is searching for Steam in `$HOME/.steam` and looking for games in `$HOME/.steam/steam`.

Is there a way to get the installer to look in the correct location? I saw that #66 had a similar issue and #55 has been closed by #70, but I am still having this issue. Any suggestions?

**Comment by rockerbacon** [comment] 2020-06-06 17:41
Duplicate of #72. I'll be working on a fix over this weekend

**Comment by balajsra** [comment] 2020-06-07 03:30
Thank you for your work! However, I am still getting issues with version 2.7.1. See output below.

[lutris-mod-organizer.log](https://github.com/rockerbacon/lutris-skyrimse-installers/files/4741349/lutris-mod-organizer.log)

The new version is correctly finding Steam in `$HOME/.local/share/Steam', but it is searching for game in library `$HOME/.local/share/Steam/steam`. As previously mentioned, it should be looking for the game installation in `$HOME/.local/share/Steam/steamapps/common`.

**Comment by balajsra** [comment] 2020-06-07 21:10
Apologies for opening this issue again, but I am still having problems installing. I tried version 2.7.2 and got the output shown below.

[lutris-mod-organizer-2.7.2.log](https://github.com/rockerbacon/lutris-skyrimse-installers/files/4742945/lutris-mod-organizer.log)

The script finds `$HOME/.local/share/Steam` correctly, as in 2.7.1.

When grep is attempted, it looks for `$HOME/.local/share/Steam/steam/steamapps/libraryfolders.vdf` and says _no such file or directory_.

Looking at my filesystem, I found `libraryfolders.vdf` in `$HOME/.local/share/Steam/steamapps/libraryfolders.vdf`.

The contents of `libraryfolders.vdf` are shown below:
```
"LibraryFolders"
{
        "TimeNextStatsReport"           "1591571589"
        "ContentStatsID"                "6832582536540301646"
}
```

After attempting grep, the script searches for the game in library `$HOME/.local/share/Steam/steam`.
The contents of this directory are:
* cached (folder)
* games (folder)
* legacydepotdata.vdf

I don't believe this is the correct folder to be looking in for APPID **22370**.

Looking at `find-library-for-appid.sh` lines 37-43, I see that the script is attempting to look for the `compatdata` folder with the APPID folder inside that:
```
for libdir in "${steam_libraries[@]}"; do
	echo "Searching for game in library '$libdir'" >&2
	if [ -d "$libdir/steamapps/compatdata/$appid" ]; then
		echo "Found game" >&2
		break
	fi
done
```

Thus, I believe the error is in the setting of `main_library`. It gets set to `$steam_install/steam` which causes the other paths to become broken. This is in line 26 of `find-library-for-appid.sh`.

**Comment by rockerbacon** [comment] 2020-06-08 13:45
I'm sorry for that. Progress on this one is naturally slow because I don't have a system to properly test things.

I released another fix. If it solves your problem feel free to close the issue again.

**Comment by balajsra** [comment] 2020-06-08 14:15
@rockerbacon No worries, I understand that it can be difficult to debug without direct access to the system. I will do my best to provide information.

That being said, I tried running 2.7.3 and it seems to have fixed the previous issue of not finding Fallout 3 GOTY, but it now has a different issue.

[lutris-mod-organizer-2.7.3.log](https://github.com/rockerbacon/lutris-skyrimse-installers/files/4746459/lutris-mod-organizer-2.7.3.log)

This is the error message. As suggested, I attempted `wineboot -u`, but it didn't fix anything.
```
wine cmd.exe /c echo '%AppData%' returned unexpanded string 'C:\Program Files' ... this can be caused by a corrupt wineprefix (`wineboot -u` may help), by an old wine, or by not owning /home/sravan/.local/share/Steam/steamapps/compatdata/22370/pfx
```

It may not be an issue with script at this point, perhaps I have not configured wine correctly. Do you have any ideas for why I might be encountering this error?

**Comment by rockerbacon** [comment] 2020-06-08 14:44
This is exactly what the error says, a "corrupted" prefix. It's usually caused by using incompatible versions of Wine in the same prefix.

1. Purge the prefix with:
```
rm -rf /home/sravan/.local/share/Steam/steamapps/compatdata/22370
```
2. In Steam: make sure Fallout 3 is configured to use Proton 5 and launch it. A clean prefix will be created
3. Reinstall Mod Organizer 2

**Comment by balajsra** [comment] 2020-06-08 15:07
I attempted the following:
1. Remove Fallout 3 GOTY compatdata folder
2. Steam -> Fallout 3 Game of the Year Edition -> Properties -> General -> Force the use of a specific Steam Play compatibiltiy tool -> Proton 5.0-8
3. I then ran the game and saw that the prefix was created
4. Attempted to reinstall Mod Organizer 2 and got the same error

**Comment by rockerbacon** [comment] 2020-06-08 15:23
What's the output for `ls -ld /home/sravan/.local/share/Steam/steamapps/compatdata/22370/pfx`?

**Comment by balajsra** [comment] 2020-06-08 16:08
Sorry for the delay, I completely re-installed Fallout 3 to see if that would resolve the issue... it did not.

```
ls -ld /home/sravan/.local/share/Steam/steamapps/compatdata/22370/pfx
drwxr-xr-x 4 sravan sravan 4096 Jun  8 12:05 /home/sravan/.local/share/Steam/steamapps/compatdata/22370/pfx/
```
I'm not sure this is the output you were looking for (-d argument). Here is the output with just -l flag.

```
ls -l /home/sravan/.local/share/Steam/steamapps/compatdata/22370/pfx
total 2716
drwxr-xr-x 2 sravan sravan    4096 Jun  8 12:02 dosdevices/
drwxr-xr-x 9 sravan sravan    4096 Jun  8 12:05 drive_c/
-rw-r--r-- 1 sravan sravan 2664356 Jun  8 12:05 system.reg
-rw-r--r-- 1 sravan sravan    3358 Jun  8 12:01 userdef.reg
-rw-r--r-- 1 sravan sravan  101370 Jun  8 12:05 user.reg
```

**Comment by rockerbacon** [comment] 2020-06-30 15:14
I'm sorry it took me so long to get back to you. I legitimately do not know what might be causing this problem. The '-d' option was to check if the directory permissions were correct as my research suggested this could be the issue.

I renamed the issue to reflect its current status and added a "help wanted" label to see if more people will help with this issue.

**Comment by balajsra** [comment] 2020-06-30 22:44
No worries. I'm currently playing some other games, but if I return to Fallout 3 and I am able to find a solution, I'll submit a pull request.

**Closed** 2023-07-17 20:21 UTC
Labels: bug, help wanted, fallout3
