### ISSUE TITLE
Nexus Links not being handled on SteamDeck

### ISSUE THREAD

**Issue by Noncorporeal** [rockerbacon/modorganizer2-linux-installer#425] opened 2022-12-02 00:37 UTC
I've been trying to get Mod Manager to manage nexus links, but I keep getting firefox telling me that there's nothing set up to handle the links. It gives me a list of options of programs to handle the link, but MO2 isn't in the list. I've looked everywhere for a solution, but I just can't seem to find one.

**Comment by TaPO4eg3D** [comment] 2022-12-09 19:53
1. Go to ~/.local/share/applications/
2. Delete "NoDisplay=true" in modorganizer2-nxm-handler.desktop
3. Restart browser if you had it opened
4. Try to download a mod
5. Firefox will ask an application, press "Show More" and select "Mod Organizer 2"

**Comment by jmaris** [comment] 2022-12-11 16:27
> 

This is all good, but in the future would there be an alternative way to do this without making the filesytem writable ?

**Comment by Martan404** [comment] 2023-01-22 09:11
I almost got it to work without protontricks but now I am stuck.

This is what my modorganizer2-nxm-handler.desktop look like right now

`[Desktop Entry]
Type=Application
Categories=Game;
Exec=bash -c 'env "STEAM_COMPAT_CLIENT_INSTALL_PATH=$HOME/.steam/steam" "STEAM_COMPAT_DATA_PATH=$HOME/.steam/steam/steamapps/compatdata/489830" "$HOME/.local/share/Steam/steamapps/common/Proton 6.3/proton" run "$HOME/Games/mod-organizer-2-skyrimspecialedition/modorganizer2/nxmhandler.exe" %u'
Name=Mod Organizer 2 NXM Handler
MimeType=x-scheme-handler/nxm;
`
For some reason Mod Organizer 2 won't accept the nxm links any more.

**Comment by Martan404** [comment] 2023-01-22 09:16
I GOT IT WORKING! I had to add "" around %u

Working shortcut, no need for protontricks or .sh scripts

`[Desktop Entry]
Type=Application
Categories=Game;
Exec=bash -c 'env "STEAM_COMPAT_CLIENT_INSTALL_PATH=$HOME/.steam/steam" "STEAM_COMPAT_DATA_PATH=$HOME/.steam/steam/steamapps/compatdata/489830" "$HOME/.local/share/Steam/steamapps/common/Proton 6.3/proton" run "$HOME/Games/mod-organizer-2-skyrimspecialedition/modorganizer2/nxmhandler.exe" "%u"'
Name=Mod Organizer 2 NXM Handler
MimeType=x-scheme-handler/nxm;
`

**Comment by Kiaos** [comment] 2023-02-04 09:43
I just did that and it opened the same window.

**Comment by rockerbacon** [comment] 2023-07-17 20:05
Links don't work when Flatpaks are involved.

Duplicate of #317

**Closed by rockerbacon** 2023-07-17 20:05 UTC

**Comment by gbdrbob** [comment] 2024-06-16 16:32
> I GOT IT WORKING! I had to add "" around %u
> 
> Working shortcut, no need for protontricks or .sh scripts
> 
> `[Desktop Entry]` `Type=Application` `Categories=Game;`
> 
> `Exec=bash -c 'env "STEAM_COMPAT_CLIENT_INSTALL_PATH=$HOME/.steam/steam" "STEAM_COMPAT_DATA_PATH=$HOME/.steam/steam/steamapps/compatdata/489830" "$HOME/.local/share/Steam/steamapps/common/Proton 6.3/proton" run "$HOME/Games/mod-organizer-2-skyrimspecialedition/modorganizer2/nxmhandler.exe" "%u"'`
> 
> `Name=Mod Organizer 2 NXM Handler` `MimeType=x-scheme-handler/nxm;`

This may work but will only pass nxm links to a single instance of MO2 (Skyrim SE in the example above), the [modorganizer2-nxm-broker.sh](https://github.com/rockerbacon/modorganizer2-linux-installer/blob/master/handlers/modorganizer2-nxm-broker.sh) script works out which game an nxm link is for and passes the link to the appropriate instance of MO2 when you have more than one modded game installed.

Using the steps [TaPO4eg3D](https://github.com/TaPO4eg3D) [suggested upthead](https://github.com/rockerbacon/modorganizer2-linux-installer/issues/425#issuecomment-1344725477) I managed to get the standard nxm handler working on my steam deck. However instead of disabling the seam-os read only mode, I installed [rwfus](https://github.com/ValShaped/rwfus) before installing [protontricks-git from AUR](https://aur.archlinux.org/packages/protontricks-git). **Beware** rwfus can brick your system if you try to do a general update of all packages using pacman, **[read the warnings on the rwfus github page](https://github.com/ValShaped/rwfus?tab=readme-ov-file#-jank-warning)** . However I believe it is safer than turning off read-only mode and it should survive an OS update. I may be pushing it installing base-devel, it has worked fine so far for me, but I haven't had a steamOS update yet, so do the below at your own risk):

Install [modorganizer2-linux-installer](modorganizer2-linux-installer) according to the README and ensure you have removed any alias set up for the flatpak version of protontricks if it is installed. Then execute the following console commands in your deck's home directory (you'll need to have [set a password](https://steamdecktips.com/blog/how-to-set-a-password-for-your-steam-deck-user-in-desktop-mode) for the deck user):

```
cd ~
sed -i '/NoDisplay/d' "/home/deck/.local/share/applications/modorganizer2-nxm-handler.desktop"
git clone -b v0.5.0 https://github.com/ValShaped/rwfus.git
cd rwfus/
./rwfus --install
./rwfus --enable
mkdir ~/builds
cd ~/builds
sudo pacman -S base-devel
git clone https://aur.archlinux.org/protontricks-git.git
cd protontricks-git/
makepkg -si
```
