### ISSUE TITLE
ERROR: redirector binaries not found

### ISSUE THREAD

**Issue by coolst3r** [rockerbacon/modorganizer2-linux-installer#510] opened 2023-07-28 09:35 UTC
I installed all dependencies and restarted running arch linux

**Comment by rockerbacon** [comment] 2023-07-28 18:00
Duplicate of #433, you downloaded the source code instead of the release. You need to compile the redirector binaries yourself if you want to install from source.

**Closed by rockerbacon** 2023-07-28 18:00 UTC
