### ISSUE TITLE
Install Fails For Skyrim SE After Finding Game

### ISSUE THREAD

**Issue by Static-Dragon** [rockerbacon/modorganizer2-linux-installer#168] opened 2020-11-07 19:45 UTC
Script output reports that it can find the game's path, but lutris will throw an error saying it cannot, please see the below log:

Running flatpaked Steam on Arch Linux
Game installed to a secondary hard drive, path is: /mnt/Games/SteamLibrary/steamapps/common/Skyrim Special Edition

Please note, it also appears that /home/static-dragon/.cache/lutris/installer/mod-organizer-2/successful-prefix-preparation doesn't exist.

```
`lutris-wrapper: /usr/bin/bash
Running /usr/bin/bash -c # clear envs set by Lutris
export LD_LIBRARY_PATH=""

nexus_game_id=skyrimspecialedition
runner=proton

if [ ! -f "/home/static-dragon/.cache/lutris/installer/mod-organizer-2/gamesinfo/$nexus_game_id.sh" ]; then
    "/home/static-dragon/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Could not find gameinfo for '$nexus_game_id', remove Lutris cache and try again"
    exit 1
fi

source "/home/static-dragon/.cache/lutris/installer/mod-organizer-2/gamesinfo/$nexus_game_id.sh"

if [ -z "$game_appid" ]; then
    echo "ERROR: empty game_appid" >&2
    exit 1
elif [ -z "$game_steam_subdirectory" ]; then
    echo "ERROR: empty steam_subdirectory" >&2
    exit 1
fi

shared="/home/static-dragon/.local/share/modorganizer2"

case "$runner" in
    proton)
        mo2_tricks="vcrun2019"
        mo2_options=""

        if [ -z "$steam_library" ]; then
            steam_library=$("/home/static-dragon/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh" $game_appid)
        fi

        if [ ! -d "$steam_library" ]; then
            "/home/static-dragon/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
                "Could not find '$game_steam_subdirectory' in your Steam library"
            exit 1
        fi

        game_prefix="$steam_library/steamapps/compatdata/$game_appid/pfx"
        game_installation="$steam_library/steamapps/common/$game_steam_subdirectory"
        game_tricks="$game_protontricks"

        echo -e \
        "#!/bin/bash\n\n'$shared/proton-launcher.sh' $mo2_options $game_proton_options \"\$@\" $game_appid '/home/static-dragon/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe'" \
        > "/home/static-dragon/Games/mod-organizer-2/run.sh"

        echo -e \
        "#!/bin/bash\n\n'$shared/proton-launcher.sh' $mo2_options $game_proton_options $game_appid '/home/static-dragon/Games/mod-organizer-2/ModOrganizer2/nxmhandler.exe' \"\$1\"" \
        > "/home/static-dragon/Games/mod-organizer-2/download.sh"
        ;;

    wine)
        mo2_tricks="vcrun2019 dotnet40"
        mo2_options="--proton-wine --winever 5.*"

        "/home/static-dragon/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" warnbox \
            "As of version 5.7, Wine still does not fully support Mod Organizer 2.2.1 and later.\nFor this reason this installer uses the Wine version bundled with Proton 5.0.\nMake sure you have Steam and Proton 5.0 installed on your system"

        game_prefix=$( \
            "/home/static-dragon/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" directorypicker \
                "Inform the path to your wineprefix" \
        )
        if [ -z "$game_prefix" ]; then
            echo "ERROR: Installation canceled by user" >&2
            exit 1
        fi

        game_tricks="$game_winetricks"

        install_path_candidates=( \
            "$game_prefix/drive_c/Program Files (x86)/Steam/steamapps/common/$game_steam_subdirectory" \
            "$game_prefix/drive_c/GOG Games/$game_steam_subdirectory" \
        )
        if [ -n "$game_gog_subdirectory" ]; then
            install_path_candidates+=( \
                "$game_prefix/drive_c/GOG Games/$game_gog_subdirectory" \
            )
        fi
        if [ "$nexus_game_id" == "fallout3" ]; then
            install_path_candidates+=( \
                "$game_prefix/drive_c/Program Files (x86)/Steam/steamapps/common/Fallout 3" \
                "$game_prefix/drive_c/GOG Games/Fallout 3" \
            )
        fi

        for path in "${install_path_candidates[@]}"; do
            echo "Searching for game at '$path'"
            if [ -d "$path" ]; then
                echo "Found game"
                game_installation="$path"
                break
            fi
        done

        if [ -z "$game_installation" ]; then
            game_installation=$( \
                "/home/static-dragon/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" directorypicker \
                    "Could not automatically find the game.\nPlease inform the path where the game is installed" \
            )
            if [ -z "$game_installation" ]; then
                echo "ERROR: installation canceled by user" >&2
                exit 1
            fi
        fi

        # TODO: uncomment once Wine fixes issues with VC2019
        # winever=$( \
        #     "/home/static-dragon/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" textentry \
        #         "Inform which version of Wine you're using\nLeave as * to use the latest version available on Lutris" \
        #         "*" \
        # )
        # if [ -z "$winever" ]; then
        #     echo "ERROR: Installation canceled by user" >&2
        #     exit 1
        # fi

        echo -e \
        "#!/bin/bash\n\nWINEPREFIX='$game_prefix' '$shared/wine-launcher.sh' $mo2_options $game_wine_options \"\$@\" '/home/static-dragon/Games/mod-organizer-2/ModOrganizer2/ModOrganizer.exe'" \
        > "/home/static-dragon/Games/mod-organizer-2/run.sh"

        echo -e \
        "#!/bin/bash\n\nWINEPREFIX='$game_prefix' '$shared/wine-launcher.sh' $mo2_options $game_wine_options '/home/static-dragon/Games/mod-organizer-2/ModOrganizer2/nxmhandler.exe' \"\$1\"" \
        > "/home/static-dragon/Games/mod-organizer-2/download.sh"
        ;;
esac

if [ -d "/home/static-dragon/.cache/lutris/installer/mod-organizer-2/${nexus_game_id}-script-extender" ]; then
    echo "Installing script extender..."

    output=$( \
        cp -af \
        "/home/static-dragon/.cache/lutris/installer/mod-organizer-2/${nexus_game_id}-script-extender/." \
        "$game_installation/" 2>&1 \
    )
    if [ "$?" != "0" ]; then
        "/home/static-dragon/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
            "Error while installing script extender: $output"
        exit 1
    fi
fi

mkdir -p "$game_prefix/drive_c/java"
output=$( \
    cp -af \
    "/home/static-dragon/.cache/lutris/installer/mod-organizer-2/extracted-openjdk/." \
    "$game_prefix/drive_c/java/" 2>&1 \
)
if [ "$?" != "0" ]; then
    "/home/static-dragon/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Error while installing OpenJDK: $output"
    exit 1
fi

WINEPREFIX="$game_prefix" \
"/home/static-dragon/.local/share/lutris/runtime/winetricks/winetricks" -q $mo2_tricks $game_tricks
if [ "$?" != "0" ]; then
    "/home/static-dragon/.cache/lutris/installer/mod-organizer-2/utils/dialog.sh" errorbox \
        "Error while installing winetricks, please run Lutris from a terminal and check the logs"
    exit 1
fi

# workaround to stop installation if command fails
echo "success" > '/home/static-dragon/.cache/lutris/installer/mod-organizer-2/successful-prefix-preparation'
Initial process has started with pid 195242
Game is considered started.
Searching for Steam in ''
Steam not found in this install path
Searching for Steam in '/home/static-dragon/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Found Steam
Searching for game in library '/home/static-dragon/.var/app/com.valvesoftware.Steam/.local/share/Steam'
Searching for game in library '/mnt/Games/SteamLibrary'
Found game
/home/static-dragon/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 44: return: can only `return' from a function or sourced script
Searching for game in library '/mnt/Games/SSD/SteamLibrary'
Found game
/home/static-dragon/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 44: return: can only `return' from a function or sourced script
ERROR: could not find game with APPID '489830'
/home/static-dragon/.cache/lutris/installer/mod-organizer-2/utils/find-library-for-appid.sh: line 49: return: can only `return' from a function or sourced script
`
```

**Comment by Static-Dragon** [comment] 2020-11-07 20:06
I should also note, I'm using the current GloriousEggroll proton patch

**Comment by rockerbacon** [comment] 2020-11-08 16:09
Don't use GloriousEggroll, see #102 

Looking at the logs it seems like you moved the game from `/mnt/Games/SteamLibrary` to `/mnt/Games/SSD/SteamLibrary` or vice-versa at some point. This is possibly a duplicate of #160

**Comment by univrsal** [comment] 2020-12-19 16:53
I ran into the same problem and it seems like you have to change all occurrences of "return" to "exit" in [find-library-for-appid.sh](https://github.com/rockerbacon/lutris-skyrimse-installers/blob/master/utils/find-library-for-appid.sh) as that seems to be the correct way of stopping with an exit code. Another issue that I faced was the winetricks version shipped with lutris not working, so I changed [this](https://github.com/rockerbacon/lutris-skyrimse-installers/blob/master/installers/modorganizer2.yml#L320) line to ``winetricks -q $mo2_tricks $game_tricks`` to make the installer use the system wintricks, which worked. I also had to remove [the check below](https://github.com/rockerbacon/lutris-skyrimse-installers/blob/master/installers/modorganizer2.yml#L321-L325) to get rid of the error message. After those patches the installer ran fine and Mod Organizer worked.
So maybe it would be possible to in-cooperate them into the installer (the latter maybe being an option to use system winetricks).

**Comment by rulatir** [comment] 2021-03-13 20:48
It doesn't bode well that a glaring programming error in the usage of a basic language construct in a shell script component of this project remains without an official fix for months.

**Comment by univrsal** [comment] 2021-03-13 23:19
I linked all the files and lines that I needed to change. I edited them and then ran the installer form the command line.

**Closed** 2023-07-17 20:20 UTC
Labels: question
