### ISSUE TITLE
NXM download doesn't work (without flatpak)

### ISSUE THREAD

**Issue by acuteaura** [rockerbacon/modorganizer2-linux-installer#555] opened 2024-01-12 22:12 UTC
protontricks installed via package manager, nixpkgs-unstable

This is the output from protontricks-launch:

```
protontricks (WARNING): Current Steam Runtime not recognized by Protontricks.
fsync: up and running.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
0078:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0078:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0078:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
0078:fixme:hid:handle_IRP_MN_QUERY_ID Unhandled type 00000005
Authorization required, but no authorization protocol specified

0104:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0104:err:winediag:nodrv_CreateWindow L"The explorer process failed to start."
0104:err:systray:initialize_systray Could not create tray window
0140:fixme:oleacc:find_class_data unhandled window class: L"#32769"
0140:fixme:uiautomation:uia_get_providers_for_hwnd Override provider callback currently unimplemented.
0140:fixme:uiautomation:msaa_provider_GetPropertyValue Unimplemented propertyId 30024
00f0:err:winediag:gnutls_process_attach failed to load libgnutls, no support for encryption
00f0:err:winediag:process_attach failed to load libgnutls, no support for pfx import/export
0140:fixme:uiautomation:msaa_fragment_get_FragmentRoot 000000000038BAF8, 000000000022FA90: stub!
0140:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0140:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
0140:err:tabtip:wWinMain Failed to create hwnd!
00f0:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
00f0:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."
00f0:fixme:win:RegisterPowerSettingNotification (000000000003003A,{02731015-4510-4526-99e6-e5a17ebd1aea},0): stub
00f0:fixme:shell:SHGetStockIconInfo (80, 0x101, 000000000012CE60) semi-stub
00f0:fixme:shell:SHGetStockIconInfo flags 0x101 not implemented
QPixmap::fromWinHICON(), failed to GetIconInfo() (Invalid cursor handle.)
00f0:fixme:shell:SHGetStockIconInfo (80, 0x100, 000000000012CE60) semi-stub
00f0:fixme:shell:SHGetStockIconInfo flags 0x100 not implemented
QPixmap::fromWinHICON(), failed to GetIconInfo() (Invalid cursor handle.)
00f0:fixme:shell:SHGetStockIconInfo (80, 0x101, 000000000012CC80) semi-stub
00f0:fixme:shell:SHGetStockIconInfo flags 0x101 not implemented
QPixmap::fromWinHICON(), failed to GetIconInfo() (Invalid cursor handle.)
00f0:err:d3d:wined3d_caps_gl_ctx_create Failed to create a window.
00f0:err:d3d:wined3d_adapter_gl_init Failed to get a GL context for adapter 0000000000296F60.
00f0:fixme:system:EnableNonClientDpiScaling (0000000000030058): stub
EnableNonClientDpiScaling() failed for HWND 0x30058 (120) (Call not implemented.)
WindowCreationData::create: CreateWindowEx failed (Success.)
Failed to create platform window for QWidgetWindow(0x250ab70, name="QMessageBoxClassWindow") with flags QFlags<Qt::WindowType>(Dialog|MSWindowsFixedSizeDialogHint|WindowTitleHint|WindowS
ystemMenuHint|WindowCloseButtonHint)
QWindowsNativeInterface::nativeResourceForWindow: 'handle' requested for null window or window without handle.
00f0:fixme:system:EnableNonClientDpiScaling (0000000000040058): stub
EnableNonClientDpiScaling() failed for HWND 0x40058 (120) (Call not implemented.)
WindowCreationData::create: CreateWindowEx failed (Success.)
Failed to create platform window for QWidgetWindow(0x250ab70, name="QMessageBoxClassWindow") with flags QFlags<Qt::WindowType>(Dialog|MSWindowsFixedSizeDialogHint|WindowTitleHint|WindowS
ystemMenuHint|WindowCloseButtonHint)
```

It then remains hanging, and doesn't add the download.

The "Authorization" message is interesting since it seems to indicate broken X11 auth, but I have no problems launching anything else and `$XAUTHORITY` is set by SDDM as shown by root firefox test:tm:.

```
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/xauth_dvJrBT which is owned by aurelia.)
```

(also, it's a wayland session, so it's all XWayland anyway)

**Comment by rockerbacon** [comment] 2024-01-13 11:03
> 0140:err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.
0140:err:winediag:nodrv_CreateWindow L"Make sure that your X server is running and that $DISPLAY is set correctly."

This is probably the culprit, Wine (Proton) is failing to find the X server. What Wayland compositor are you using?

There are many reasons why the communication between Wine and the XWayland server might fail. I'd start by investigating protontricks-launch. See if it is working properly on your system and if it works with the specific Proton version you're trying to use.

**Comment by acuteaura** [comment] 2024-01-13 18:21
> What Wayland compositor are you using?

KWin

>[not our bug label]

it seems you might be right, it's probably a NixOS bug

https://discourse.nixos.org/t/cannot-use-wine-graphical-interface-using-protontricks/23038

**Comment by acuteaura** [comment] 2024-01-15 15:45
Okay, did some more research.

* Protontricks is a year out of date on nixpkgs, and the PR to update it has been abandoned due to having to patch nix-isms (https://github.com/NixOS/nixpkgs/pull/262553)
* There's a bug in 10.1 involving bwrap and kwin on wayland not passing environments properly
* You can bypass the issue by adding `--no-bwrap --background-wineserver` to modorganizer2-nxm-broker.sh, but then you need to launch it with an NXM link / protontricks with these arguments *or* Steam to not have two instances on one profile.

**Comment by rockerbacon** [comment] 2024-01-23 15:35
#560 added additional instructions to help users check where they can get an up-to-date version of Protontricks. This is the best I can do so long as the project depends on Protontricks and requires users to install it themselves.

@acuteaura I know it kind of defeats the purpose of using NixOS but the solution for you may be to get Protontricks from pipx.

Closing the issue, since it was confirmed to be caused by a bug in an older version of Protontricks that was fixed in a future release.

**Closed by rockerbacon** 2024-01-23 15:35 UTC
Labels: question, not our bug

**Comment by acuteaura** [comment] 2024-01-28 13:37
NixOS got 1.11.0 the other day, and somehow it still leads to a steam-launched instance not being aware of a protontricks-launched instance.
