### ISSUE TITLE
EnableNonClientDPI Scaling() Failed

### ISSUE THREAD

**Issue by Th3b3n** [rockerbacon/modorganizer2-linux-installer#467] opened 2023-04-22 15:03 UTC
Terminal and MO2 log spam this error message for HWND  0x "3016e" (the value here changes). The longer Mo2 runs, the more bogged down my syssem gets as this error doesn't stop occuring. I've tried googling it for a fix.. but the info is beyond my ability at this time.

**Comment by alghostzx** [comment] 2023-05-23 14:54
it seems to be an error caused by a non implemented call in proton, but in my experience is doesn't affect the program's operation.

**Comment by itspngu** [comment] 2023-07-09 08:30
If it bothers you, you can drop a `qt.conf` file in the directory containing the ModOrganizer.exe, with the following contents:

```
[Platforms]
WindowsArguments = dpiawareness=2
```

**Comment by rockerbacon** [comment] 2023-07-16 14:16
Duplicate of #409

**Closed by rockerbacon** 2023-07-16 14:16 UTC
